<?php

return [
    'app' => [
        'name' => 'Umera Certificate Manager',
        'org' => 'Umera Business School',
        'domain' => 'https://cert.umbs.ng',
    ],
    'programs' => [
        ['id' => 'umb5', 'name' => 'UmeraBoost 5.0', 'year' => '2026'],
    ],
    'certificate' => [
        'name' => 'Adeyemo Goodness',
        'email' => 'goodness@example.com',
        'course' => 'Fundamentals of Generative Artificial Intelligence',
        'course_code' => 'GAI',
        'program' => 'UmeraBoost 5.0',
        'program_code' => 'UMB5',
        'certificate_id' => 'UMB5-GAI-2026-000001',
        'issue_date' => 'October 1, 2026',
        'issue_date_iso' => '2026-10-01',
        'type' => 'Certificate of Completion',
        'issuer' => 'Umera Business School',
    ],
    'stats' => [
        'participants' => 1248,
        'eligible' => 1087,
        'certificates_issued' => 1087,
        'downloaded' => 921,
        'not_downloaded' => 166,
        'revoked' => 3,
        'not_eligible' => 131,
        'pending_review' => 30,
        'total_downloads' => 2847,
        'unique_downloads' => 921,
        'download_rate' => 84.7,
        'total_verifications' => 4152,
        'valid_verifications' => 3894,
        'invalid_verifications' => 219,
        'revoked_checks' => 39,
    ],
    'participants' => [
        ['name' => 'Adeyemo Goodness', 'email' => 'goodness@example.com', 'course' => 'Fundamentals of Generative AI', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'eligible', 'certificate' => 'issued', 'downloaded' => true, 'id' => 'UMB5-GAI-2026-000001'],
        ['name' => 'Chidera Okafor', 'email' => 'chidera@example.com', 'course' => 'Fundamentals of Generative AI', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'eligible', 'certificate' => 'issued', 'downloaded' => true, 'id' => 'UMB5-GAI-2026-000002'],
        ['name' => 'Ibrahim Musa', 'email' => 'ibrahim@example.com', 'course' => 'Digital Marketing Essentials', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'eligible', 'certificate' => 'issued', 'downloaded' => false, 'id' => 'UMB5-DME-2026-000003'],
        ['name' => 'Fatima Abdullahi', 'email' => 'fatima@example.com', 'course' => 'Data Science Fundamentals', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'eligible', 'certificate' => 'issued', 'downloaded' => true, 'id' => 'UMB5-DSF-2026-000004'],
        ['name' => 'Temitope Johnson', 'email' => 'temitope@example.com', 'course' => 'Fundamentals of Generative AI', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'pending', 'certificate' => 'pending', 'downloaded' => false, 'id' => 'UMB5-GAI-2026-000005'],
        ['name' => 'Emeka Nwankwo', 'email' => 'emeka@example.com', 'course' => 'Entrepreneurship Skills', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'not_eligible', 'certificate' => 'none', 'downloaded' => false, 'id' => null],
        ['name' => 'Aisha Bello', 'email' => 'aisha@example.com', 'course' => 'Digital Marketing Essentials', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'eligible', 'certificate' => 'issued', 'downloaded' => false, 'id' => 'UMB5-DME-2026-000006'],
        ['name' => 'David Adeleke', 'email' => 'david@example.com', 'course' => 'Data Science Fundamentals', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'eligible', 'certificate' => 'revoked', 'downloaded' => true, 'id' => 'UMB5-DSF-2026-000007'],
        ['name' => 'Blessing Eze', 'email' => 'blessing@example.com', 'course' => 'Fundamentals of Generative AI', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'eligible', 'certificate' => 'issued', 'downloaded' => true, 'id' => 'UMB5-GAI-2026-000008'],
        ['name' => 'Samuel Lawal', 'email' => 'samuel@example.com', 'course' => 'Entrepreneurship Skills', 'program' => 'UmeraBoost 5.0', 'eligibility' => 'pending', 'certificate' => 'pending', 'downloaded' => false, 'id' => null],
    ],
    'activity' => [
        ['action' => 'Certificate downloaded', 'user' => 'Chidera Okafor', 'target' => 'UMB5-GAI-2026-000002', 'date' => '2 mins ago', 'status' => 'success'],
        ['action' => 'Certificate verified', 'user' => 'Public Visitor', 'target' => 'UMB5-GAI-2026-000001', 'date' => '8 mins ago', 'status' => 'success'],
        ['action' => 'Admin imported participants', 'user' => 'Admin', 'target' => '1,248 records', 'date' => '1 hour ago', 'status' => 'success'],
        ['action' => 'Certificate generated', 'user' => 'Admin', 'target' => 'UMB5-GAI-2026-000008', 'date' => '3 hours ago', 'status' => 'success'],
        ['action' => 'Eligibility updated', 'user' => 'Admin', 'target' => 'Temitope Johnson', 'date' => '5 hours ago', 'status' => 'info'],
        ['action' => 'Certificate revoked', 'user' => 'Admin', 'target' => 'UMB5-DSF-2026-000007', 'date' => '1 day ago', 'status' => 'error'],
    ],
    'recent_downloads' => [
        ['name' => 'Adeyemo Goodness', 'id' => 'UMB5-GAI-2026-000001', 'date' => 'Oct 15, 2026 14:32'],
        ['name' => 'Chidera Okafor', 'id' => 'UMB5-GAI-2026-000002', 'date' => 'Oct 15, 2026 11:18'],
        ['name' => 'Fatima Abdullahi', 'id' => 'UMB5-DSF-2026-000004', 'date' => 'Oct 15, 2026 09:05'],
        ['name' => 'Blessing Eze', 'id' => 'UMB5-GAI-2026-000008', 'date' => 'Oct 14, 2026 16:44'],
        ['name' => 'David Adeleke', 'id' => 'UMB5-DSF-2026-000007', 'date' => 'Oct 14, 2026 13:22'],
    ],
    'verifications' => [
        ['id' => 'UMB5-GAI-2026-000001', 'result' => 'Valid', 'date' => 'Oct 15, 2026 15:02', 'source' => 'Direct Link'],
        ['id' => 'UMB5-GAI-2026-000002', 'result' => 'Valid', 'date' => 'Oct 15, 2026 14:30', 'source' => 'QR Scan'],
        ['id' => 'UMB5-DSF-2026-000007', 'result' => 'Revoked', 'date' => 'Oct 15, 2026 11:12', 'source' => 'LinkedIn'],
        ['id' => 'UMB5-INV-2026-XXXXXX', 'result' => 'Not Found', 'date' => 'Oct 15, 2026 09:55', 'source' => 'Direct Link'],
        ['id' => 'UMB5-DME-2026-000003', 'result' => 'Valid', 'date' => 'Oct 14, 2026 18:41', 'source' => 'WhatsApp'],
    ],
    'certificates' => [
        ['id' => 'UMB5-GAI-2026-000001', 'participant' => 'Adeyemo Goodness', 'course' => 'Fundamentals of Generative AI', 'issue_date' => 'Oct 01, 2026', 'status' => 'issued', 'downloads' => 7, 'verifications' => 42],
        ['id' => 'UMB5-GAI-2026-000002', 'participant' => 'Chidera Okafor', 'course' => 'Fundamentals of Generative AI', 'issue_date' => 'Oct 01, 2026', 'status' => 'issued', 'downloads' => 3, 'verifications' => 18],
        ['id' => 'UMB5-DME-2026-000003', 'participant' => 'Ibrahim Musa', 'course' => 'Digital Marketing Essentials', 'issue_date' => 'Oct 01, 2026', 'status' => 'issued', 'downloads' => 0, 'verifications' => 5],
        ['id' => 'UMB5-DSF-2026-000004', 'participant' => 'Fatima Abdullahi', 'course' => 'Data Science Fundamentals', 'issue_date' => 'Oct 01, 2026', 'status' => 'issued', 'downloads' => 4, 'verifications' => 22],
        ['id' => 'UMB5-GAI-2026-000005', 'participant' => 'Temitope Johnson', 'course' => 'Fundamentals of Generative AI', 'issue_date' => '—', 'status' => 'pending', 'downloads' => 0, 'verifications' => 0],
        ['id' => 'UMB5-DSF-2026-000007', 'participant' => 'David Adeleke', 'course' => 'Data Science Fundamentals', 'issue_date' => 'Oct 01, 2026', 'status' => 'revoked', 'downloads' => 2, 'verifications' => 3],
        ['id' => 'UMB5-DME-2026-000006', 'participant' => 'Aisha Bello', 'course' => 'Digital Marketing Essentials', 'issue_date' => 'Oct 01, 2026', 'status' => 'issued', 'downloads' => 0, 'verifications' => 9],
        ['id' => 'UMB5-GAI-2026-000008', 'participant' => 'Blessing Eze', 'course' => 'Fundamentals of Generative AI', 'issue_date' => 'Oct 02, 2026', 'status' => 'issued', 'downloads' => 5, 'verifications' => 31],
    ],
    'eligibility' => [
        ['participant' => 'Adeyemo Goodness', 'course' => 'Fundamentals of Generative AI', 'registration' => 'Registered', 'attendance' => '95%', 'assessment' => '92%', 'completion' => 'Completed', 'eligibility' => 'eligible'],
        ['participant' => 'Chidera Okafor', 'course' => 'Fundamentals of Generative AI', 'registration' => 'Registered', 'attendance' => '88%', 'assessment' => '85%', 'completion' => 'Completed', 'eligibility' => 'eligible'],
        ['participant' => 'Temitope Johnson', 'course' => 'Fundamentals of Generative AI', 'registration' => 'Registered', 'attendance' => '78%', 'assessment' => '—', 'completion' => 'In Progress', 'eligibility' => 'pending'],
        ['participant' => 'Emeka Nwankwo', 'course' => 'Entrepreneurship Skills', 'registration' => 'Registered', 'attendance' => '52%', 'assessment' => '48%', 'completion' => 'Incomplete', 'eligibility' => 'not_eligible'],
        ['participant' => 'Samuel Lawal', 'course' => 'Entrepreneurship Skills', 'registration' => 'Registered', 'attendance' => '68%', 'assessment' => '65%', 'completion' => 'Review Pending', 'eligibility' => 'pending'],
        ['participant' => 'Fatima Abdullahi', 'course' => 'Data Science Fundamentals', 'registration' => 'Registered', 'attendance' => '92%', 'assessment' => '97%', 'completion' => 'Completed', 'eligibility' => 'eligible'],
    ],
    'templates' => [
        [
            'name' => 'UmeraBoost 5.0 Certificate',
            'program' => 'UmeraBoost 5.0',
            'status' => 'active',
            'created' => 'Sep 15, 2026',
            'template_path_public' => '/images/certificate-templates/umeraboost-5.0.png',
            'template_path_resource' => resource_path('certificate-templates/umeraboost-5.0.png'),
            'template_path_storage' => storage_path('app/certificate-templates/umeraboost-5.0.png'),
            'aspect_ratio' => '1/1.414',
            'orientation' => 'portrait',
            'dynamic_fields' => [
                'name' => ['top' => '38%', 'left' => '50%', 'font_family' => "'Playfair Display', Georgia, serif", 'font_size' => 'clamp(1.25rem, 3vw, 2.5rem)', 'font_weight' => '700', 'color' => '#171717'],
                'course' => ['top' => '52.5%', 'left' => '50%', 'font_family' => "'Playfair Display', Georgia, serif", 'font_size' => 'clamp(1rem, 2vw, 1.75rem)', 'font_weight' => '600', 'color' => '#171717'],
            ],
        ],
    ],
    'certificate_template' => [
        'default' => '/images/certificate-templates/umeraboost-5.0.png',
        'aspect_ratio' => '1 / 1.414',
        'overlay' => [
            'name' => [
                'top_percent' => 37.5,
                'font_family' => "'Playfair Display', Georgia, 'Times New Roman', serif",
                'font_weight' => 700,
                'text_transform' => 'none',
                'letter_spacing' => '0.01em',
            ],
            'course' => [
                'top_percent' => 52,
                'font_family' => "'Playfair Display', Georgia, 'Times New Roman', serif",
                'font_weight' => 600,
                'text_transform' => 'none',
                'letter_spacing' => '0.005em',
            ],
        ],
    ],
    'downloads_chart' => [
        ['label' => 'Oct 01', 'value' => 87],
        ['label' => 'Oct 05', 'value' => 142],
        ['label' => 'Oct 08', 'value' => 198],
        ['label' => 'Oct 10', 'value' => 264],
        ['label' => 'Oct 12', 'value' => 312],
        ['label' => 'Oct 14', 'value' => 418],
        ['label' => 'Oct 15', 'value' => 523],
    ],
];
